### PR TITLE
Enable windows

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@kszucs all builds have passed, I believe this can be merged now.

**Comment by kszucs** [comment]
Great! Merging!

Thanks @nicoddemus !

**Comment by kszucs** [comment]
@nicoddemus Looks like osx build has failed.

**Comment by nicoddemus** [comment]
@kszucs thanks for the ping. Weird, it had passed all platforms on this PR and the failure was right at the start of the job... might be a spurious problem, I restarted the job. Let's see.

**Comment by nicoddemus** [comment]
@kszucs it now passed, so I think we can assume it was a flaky failure. 👍

**Comment by kszucs** [comment]
Thanks!

**Pull request merged**
