### PR TITLE
Added thewchan as maintainer

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
Hi @kszucs & @nicoddemus, if possible, please add me as a maintainer; another package I'm trying to add to conda-forge needs one of the newer version of Sanic as dependency. Thanks!

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
Thanks @thewchan.

One of the reasons the last versions didn't build was due to the missing `sanit-routing`. I've opened https://github.com/conda-forge/staged-recipes/pull/14753 a few days.

**Comment by thewchan** [comment]
@nicoddemus Got it, and thanks! Have you tried pinging folks in the Gitter?

**Comment by nicoddemus** [comment]
I haven't, but I've updated the recipe only a few hours ago now that the latest release includes a `LICENSE` file. 👍

**Pull request merged**
